name: Deploy Tweet Service

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Deploy Tweet Service
        env:
          DROPLET_IP: "137.184.227.182"
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          cd tweet-service
          mvn clean package -DskipTests
          echo "$SSH_KEY" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no root@$DROPLET_IP << 'EOF'
            docker rm -f tweet-service || true
            docker rmi tweet-service:latest || true
          EOF
          scp -i ssh_key.pem -r . root@$DROPLET_IP:/root/tweet-service
          ssh -i ssh_key.pem -o StrictHostKeyChecking=no root@$DROPLET_IP << 'EOF'
            cd /root/tweet-service
            docker build -t tweet-service:latest .
            docker run -d -p 8082:8082 --name tweet-service tweet-service:latest
          EOF
